version: '3.7'

volumes:
  database:

services:

  database:
    image: postgres:11
    volumes:
      - ./datastream/postgres_initdb:/docker-entrypoint-initdb.d
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: A22469000YABUTDONTREALLYUSETHISPASSWORD
      POSTGRES_USER: datastreamuser
      POSTGRES_DB: datastream

  datastream:
    build: datastream/.
    volumes:
      - ./:/usr/local/src/
    environment:
      POSTGRES_PASSWORD: A22469000YABUTDONTREALLYUSETHISPASSWORD
      POSTGRES_USER: datastreamuser
      POSTGRES_DB: datastream
      POSTGRES_HOST: database
    stdin_open: true
    tty: true
